
_shared_config: &shared_config
  language: node_js
  os: linux
  node_js: "12"
  before_script: npm i -g nativescript
  cache:
    yarn: true
    npm: true
matrix:
  include:
    - stage: "Lint"
      <<: *shared_config
      script: npm run setup && npm run lint
    - stage: "Build"
      <<: *shared_config
      script: npm run setup && npm start @edusperoni.build-all
    # - stage: "Test"
    #   <<: *shared_config
    #   language: android
    #   dist: trusty
    #   sudo: required
    #   jdk: oraclejdk8
    #   before_script:
    #     - npm i -g nativescript
    #     - android list targets
    #     - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
    #     - emulator -avd test -no-audio -no-window &
    #     - android-wait-for-emulator
    #   before_install:
    #     - nvm install 12
    #     - yes | sdkmanager "platforms;android-29"
    #   before_cache:
    #     - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    #     - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    #   cache:
    #     yarn: true
    #     npm: true
    #     directories:
    #       - $HOME/.gradle/caches/
    #       - $HOME/.gradle/wrapper/
    #   script: npm run setup && cd apps/demo && ns test android
    # - <<: *shared_config
    #   os: osx
    #   jdk: oraclejdk8
    #   osx_image: xcode12.5
    #   cache:
    #     yarn: true
    #     npm: true
    #     cocoapods: true
    #   before_install: pip install six
    #   script: npm run setup && cd apps/demo && ns test ios


android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
